version: '3.7'

services:
  apigateway:
    build:
      context: ../APIGateway/
      dockerfile: APIGateway/Dockerfile
    ports:
      - "8887:80"
    networks:
      - netcommon

  identitycontrol:
    build:
      context: ../IdentityControl/
      dockerfile: IdentityControl/Dockerfile
    ports:
      - "8888:80"
    networks:
      - netcommon

  accountapi:
    build:
      context: ./API  # Mantém o contexto original como estava no docker-compose.yml original
      dockerfile: Dockerfile
    ports:
      - "8889:80"
    networks:
      - netcommon

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'qazsedcft'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - netcommon

  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'qazsedcft'
    ports:
      - "5672:5672"  
      - "15672:15672"  
    networks:
      - netcommon
networks:
  netcommon:

volumes:
  postgres-data: {}
