// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231108062828_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.AccountBalanceDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("AccountDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FK_Account")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AccountsBalanceDates");
                });

            modelBuilder.Entity("DAL.Models.AccountOperationDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccountBalanceAfeterOperation")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AccountBalanceBeforeOperation")
                        .HasColumnType("numeric");

                    b.Property<string>("AccountDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FK_Account")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OperationAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OperationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperationUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccountsOperationDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
